baseURL = "https://blog.totorow.xyz/"
languageCode = "en-us"
title = "Tw's blog"
copyright = "Copyright © 2012–2020"
theme = "hugo-theme-tokiwa"
disqusShortname = "totorow"
googleAnalytics = "UA-49335644-1"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Archive"
    weight = 1
    url = "/posts/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 4

[params]
useChineseFonts = true # for font Noto Serif etc.
bannerFont = "fonts/Go-Regular" # custom your own font for the title.
favicon = "/images/favicon.ico"
env = "production" # for Google Analytics and DISQUS.
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].

[social]
twitter="https://twitter.com/Totoroow"
github="https://github.com/tw4452852"
linkedin="https://www.linkedin.com/in/wei-tan-39510471"
mail="mailto:tw8445282@hotmail.com"
telegram="https://t.me/Totorow"
