baseURL = "https://totorow.xyz"
languageCode = "en-us"
title = "Tw's blog"
theme = "hugo-theme-tokiwa"

[params]
useChineseFonts = true # for font Noto Serif etc.
bannerFont = "fonts/Go-Regular" # custom your own font for the title.
